apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: hpa-deployment
 namespace: {{ .Values.namespace }}
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: {{ .Values.name }}
 minReplicas: 1
 maxReplicas: 10
 targetCPUUtilizationPercentage: 500