apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  DB_PASSWORD: MTIzNDU2 # base64 of 123456
  POSTGRES_PASSWORD: MTIzNDU2 # base64 of 123456