apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    {{- toYaml .Values.labels | nindent 4 }}
  type: {{ .Values.service.type }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }} # port on which this service will listen
      # targetPort: 8080 # port of the deployment container
      # nodePort: 30001





# apiVersion: v1
# kind: Service
# metadata:
#   name: {{ include "todo.fullname" . }}
#   labels:
#     {{- include "todo.labels" . | nindent 4 }}
# spec:
#   type: {{ .Values.service.type }}
#   ports:
#     - port: {{ .Values.service.port }}
#       targetPort: http
#       protocol: TCP
#       name: http
#   selector:
#     {{- include "todo.selectorLabels" . | nindent 4 }}
