apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- toYaml .Values.labels | nindent 6 }}
  template:
    metadata:
      labels:
        {{- toYaml .Values.labels | nindent 8 }}
    spec:
      containers:
      - name: postgres
        image: {{ .Values.image.repository }}
        env:
        - name: POSTGRES_PASSWORD
          value: "123456"
        resources: {}
        ports:
        - containerPort: 5432

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    {{- toYaml .Values.labels | nindent 4 }}
  ports:
  - port: 5432
    targetPort: 5432